name: Sync OAS to ReadMe
on:
  push:
    branches:
      - v1/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install -g speccy
      - run: speccy resolve openapi/openapi.yaml -o openapi/openapi-full.yaml
      - uses: readmeio/github-readme-sync@2.0.0
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}
          oas-file-path: openapi/openapi-full.yaml
          # api-version: 'v1.0.0'
